MockProject/FA.MockProject.Present/Models/ClassAdmin.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FA.MockProject.Present.Models
{
    public class ClassAdmin
    {
        public string ClassAdminId { get; set; }
        public string Account { get; set; }
        public string PassWord { get; set; }
        public string  FullName { get; set; }
        public DateTime DateOfBirth { get; set; }
        [Display(Name ="Male")]
        public bool Gender { get; set; }
        public string  PhoneNumber { get; set; }
        public string Email { get; set; }
        public Statuss Status { get; set; }
        public string AuditTrail { get; set; }
        public bool IsDeleted { get; set; }
        public enum Statuss:int
        {
            New,Old
        }
    }

}

MockProject/FA.MockProject.Present/Controllers/ClassAdminsController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FA.MockProject.Present.Models;
using FA.MockProject.Present.Models.Service;

namespace FA.MockProject.Present.Controllers
{
    [Authorize(Roles ="Manager")]
    public class ClassAdminsController : Controller
    {
        private readonly IClassAdminService _context;

        public ClassAdminsController(IClassAdminService context)
        {
            _context = context;
        }

        // GET: ClassAdmins
        public IActionResult Index()
        {
            return View(_context.GetAll());
        }

        // GET: ClassAdmins/Details/5
        public IActionResult Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classAdmin = _context.Details(id);
            if (classAdmin == null)
            {
                return NotFound();
            }

            return View(classAdmin);
        }

        // GET: ClassAdmins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ClassAdmins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ClassAdminId,Account,PassWord,FullName,DateOfBirth,Gender,PhoneNumber,Email,Status,AuditTrail,IsDeleted")] ClassAdmin classAdmin)
        {
            classAdmin.Status = ClassAdmin.Statuss.New;
            if (ModelState.IsValid)
            {       
                if (_context.Create(classAdmin))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(classAdmin);
        }

        // GET: ClassAdmins/Edit/5
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classAdmin = _context.Details(id);
            if (classAdmin == null)
            {
                return NotFound();
            }
            return View(classAdmin);
        }

        // POST: ClassAdmins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, [Bind("ClassAdminId,Account,PassWord,FullName,DateOfBirth,Gender,PhoneNumber,Email,Status,AuditTrail,IsDeleted")] ClassAdmin classAdmin)
        {
            if (id != classAdmin.ClassAdminId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(classAdmin,User.Identity.Name);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassAdminExists(classAdmin.ClassAdminId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(classAdmin);
        }

        // GET: ClassAdmins/Delete/5
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classAdmin = _context.Details(id);
            if (classAdmin == null)
            {
                return NotFound();
            }

            return View(classAdmin);
        }

        // POST: ClassAdmins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            var classAdmin = _context.Details(id);
            if (_context.Delete(classAdmin.ClassAdminId))
            {
                return RedirectToAction(nameof(Index));
            }
            return BadRequest();
        }

        private bool ClassAdminExists(string id)
        {
            return _context.Details(id) != null;
        }
    }
}

MockProject/FA.MockProject.Present/Views/ClassAdmins/Create.cshtml
@model FA.MockProject.Present.Models.ClassAdmin

@{
    ViewData["Title"] = "Create";
}

<h1 style="text-align:center">Create</h1>

<h4 style="text-align:center">ClassAdmin</h4>
<hr />
<div class="row" style="width:1000px; margin:0 235px;">

    <form asp-action="Create">
        <table class="table table-bordered" style="font-size:85%; width:800px;">
            <colgroup>
                <col span="1" style="width: 20%;">
                <col span="1" style="width: 50%;">
                <col span="1" style="width: 20%;">
                <col span="1" style="width: 120%;">
            </colgroup>
            <tbody>
            <tr>
                <th>
                    <label asp-for="Account" class="control-label"></label>
                </th>

                <th>
                    <input asp-for="Account" class="form-control" />
                    <span asp-validation-for="Account" class="text-danger"></span>
                </th>

                <th>
                    <label asp-for="PassWord" class="control-label"></label>
                </th>


                <th>
                    <input type="password" asp-for="PassWord" class="form-control" />
                    <span asp-validation-for="PassWord" class="text-danger"></span>

                </th>




            </tr>
            <tr>
                <th>
                    <label asp-for="FullName" class="control-label"></label>
                </th>


                <th>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>

                </th>


                <th>
                    @Html.DisplayNameFor(model => model.Gender)
                </th>
                <th>

                    <input style="vertical-align:middle" asp-for="Gender" />

                </th>
            </tr>
            <tr>

                <th>

                    <label asp-for="DateOfBirth" class="control-label"></label>
                </th>
                <th colspan="3">
                    <input asp-for="DateOfBirth" class="form-control" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </th>



            </tr>

            <tr>
                <th>
                    <label asp-for="PhoneNumber" class="control-label"></label>

                </th>
                <th>
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>

                </th>
                <th>
                    <label asp-for="Email" class="control-label"></label>
                </th>
                <th>

                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </th>
            </tr>
            </tbody>

        </table>


        @*<th> <p> <div asp-validation-summary="ModelOnly" class="text-danger"></div> </p> </th>*@
        <input type="submit" value="Create" class="btn btn-primary" />
    </form>




</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MockProject/FA.MockProject.Present/Views/ClassAdmins/Delete.cshtml
@model FA.MockProject.Present.Models.ClassAdmin

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClassAdmin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Account)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassWord)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassWord)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuditTrail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuditTrail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClassAdminId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MockProject/FA.MockProject.Present/Views/ClassAdmins/Details.cshtml
@model FA.MockProject.Present.Models.ClassAdmin

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ClassAdmin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Account)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Account)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PassWord)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PassWord)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuditTrail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuditTrail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ClassAdminId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MockProject/FA.MockProject.Present/Views/ClassAdmins/Edit.cshtml
@model FA.MockProject.Present.Models.ClassAdmin

@{
    ViewData["Title"] = "Edit";
}

<h1 style="text-align:center">Edit</h1>

<h4 style="text-align:center">Admin Profile</h4>
<hr />
<div class="row" style="width:1200px; margin:0  235px;">
   
    <form asp-action="Edit">
        <input type="hidden" asp-for="ClassAdminId" />
        <table class="table table-bordered" style="font-size:85%; width:800px;">
            <colgroup>
                <col span="1" style="width: 20%;">
                <col span="1" style="width: 50%;">
                <col span="1" style="width: 20%;">
                <col span="1" style="width: 120%;">
            </colgroup>

            <tbody>
                <tr>
                    <th>
                        <label asp-for="Account" class="control-label"></label>
                    </th>

                    <th>
                        <input asp-for="Account" class="form-control" />
                        <span asp-validation-for="Account" class="text-danger"></span>
                    </th>

                    <th>
                        <label asp-for="PassWord" class="control-label"></label>
                    </th>


                    <th>
                        <input type="password" asp-for="PassWord" class="form-control" />
                        <span asp-validation-for="PassWord" class="text-danger"></span>

                    </th>




                </tr>
                <tr>
                    <th>
                        <label asp-for="FullName" class="control-label"></label>
                    </th>


                    <th>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>

                    </th>


                    <th>
                        @Html.DisplayNameFor(model => model.Gender)
                    </th>
                    <th>

                        <input style="vertical-align:middle" asp-for="Gender" />

                    </th>
                </tr>
                <tr>

                    <th>

                        <label asp-for="DateOfBirth" class="control-label"></label>
                    </th>
                    <th colspan="3">
                        <input asp-for="DateOfBirth" class="form-control" />
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </th>



                </tr>

                <tr>
                    <th>
                        <label asp-for="PhoneNumber" class="control-label"></label>

                    </th>
                    <th>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>

                    </th>
                    <th>
                        <label asp-for="Email" class="control-label"></label>
                    </th>
                    <th>

                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </th>
                </tr>
                <tr>
                    <th>

                        @Html.DisplayNameFor(model => model.IsDeleted)

                    </th>
                    <th colspan="3">

                        <input style="vertical-align:middle" asp-for="IsDeleted" />

                    </th>
                </tr>
            <tbody>
        </table>
        <input type="submit" value="Save" class="btn btn-primary" />

    </form>
    </div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MockProject/FA.MockProject.Present/Views/ClassAdmins/Index.cshtml
@model IEnumerable<FA.MockProject.Present.Models.ClassAdmin>

@{
    ViewData["Title"] = "Index";
}

<h1 style="text-align:center">View Admin Profile</h1>

<p>
   
    <a asp-action="Create" asp-area=""
       class="btn btn-primary bg-custom float-left " style="margin-right:5px">
        <i style="font-size:15px; vertical-align: middle;" class="fas fa-plus-square"></i>
    </a>
</p>
<table class="table table-bordered"  style='font-size:85%'>
    <thead>
        <tr>
            <th>
               
                  @Html.DisplayNameFor(model => model.Account)
            </th>
    
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuditTrail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
             <a asp-action="Details" asp-controller="ClassAdmins" asp-area=""
                   asp-route-id="@item.ClassAdminId">    @Html.DisplayFor(modelItem => item.Account) </a>
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuditTrail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>


            <td style="text-align: center; vertical-align: middle;">
                <div style="width:90px;">

                    <form asp-action="Delete" asp-controller="ClassAdmins" asp-area="" asp-route-id="@item.ClassAdminId">
                        <a asp-action="Edit" asp-controller="ClassAdmins" asp-area=""
                           asp-route-id="@item.ClassAdminId" class="btn btn-primary bg-custom float-left w-auto">
                            <i style="font-size:15px; vertical-align: middle;" class="fas fa-edit"></i>
                        </a>

                        <button type="submit"
                                onclick="return confirm('Are you sure to delete ?');"
                                class="btn btn-danger float-right w-auto ">
                            <i style="font-size:15px; vertical-align: middle;" class="fas fa-trash-alt"></i>
                        </button>

                    </form>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>